### ISSUE TITLE
Test retries with deduplication plugin

### ISSUE THREAD

**Issue by jwage** [jwage/phpamqplib-messenger#66]
Does a retried/delayed message have the same message id and will it be ignored due to duplication plugin?

**Comment by jwage** [comment]
This seems to work fine. I have deduplication plugin installed and enabled on my exchange:

```yaml
framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_PHPAMQPLIB_DSN)%"
                options:
                    exchange:
                        name: async_exchange
                        type: x-message-deduplication
                        arguments:
                            x-cache-size: 100000
                            x-cache-ttl: 60000
                    queues:
                        async_messages: ~
```

Dispatching a message like this:

```php
$envelope = Envelope::wrap($message)->with(AmqpStamp::createWithAttributes(
    attributes: [
        'headers' => ['x-deduplication-header' => 'message_id'],
        'message_id' => $messageId,
    ]
));
```

When I add a DelayStamp, it goes to the delay queue and after the delay gets sent to the main queue and is handled correctly.

I also tested with retries by forcing a `RecoverableMessageHandlingException` in the message handler and the message gets retried correctly.
