### ISSUE TITLE
[Feature Request] Support for multiple bindings per queue

### ISSUE THREAD

**Issue by githoober** [jwage/phpamqplib-messenger#9]
First, I want to express my appreciation for this library as it fixes many issues with the official Symfony AMQP component by providing a pure PHP implementation for RabbitMQ connections. This makes it much easier to deploy applications without requiring the php-amqp C extension.

**Feature Request**
I would like to request support for multiple bindings per queue. This is the same limitation that exists in the official Symfony AMQP messenger component, which was reported in [symfony/symfony#37233](https://github.com/symfony/symfony/issues/37233).
For reference, the original issue (https://github.com/symfony/symfony/issues/37233) describes how the current implementation doesn't allow a queue to have more than one binding, which restricts the use of header-based exchanges and more complex routing patterns.

**Use Case**
For my application, I need to use header-based queues and exchanges to track different types of events. Most of these queues require multiple bindings, so I can listen to different event types (e.g., an update event on one model and a creation event on another model) in the same queue. This is a standard pattern in many AMQP implementations.

**Proposed Solution**
I propose adding functionality to the Connection class to support multiple bindings for a single queue. This could be implemented by introducing a new option under queues[name] called bindings[name] that would allow:

An array of binding configurations
Each binding with a 'key' string value
An 'arguments' array value per binding

```
async_consume_task:
    dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
    options:
        vhost: message-bus
        exchange:
            name: message-bus-exchange
            type: headers
        queues:
            'cart-purchases-header-queue':
                'bindings':
                    'manual-messages':
                        'arguments':
                            message-type: 'task'
                            subject: 'cart'
                            x-bind: all
                    'customer-messages':
                        'arguments':
                            message-type: 'event'
                            subject: 'customer'
                            x-bind: all
            'general-events-topic-queue':
                'bindings':
                    0:
                        'key': 'entity-change.*.*.*'
```

This would maintain backward compatibility while providing the needed flexibility for more complex messaging patterns.

**Alternative Approach**
If implementing this feature directly isn't on your roadmap, would you consider making the Connection class implement a ConnectionInterface? This would allow for easier extensibility by users who need specialized binding configurations.
Thank you for considering this feature request. I'm happy to provide more details or contribute to the implementation if that would be helpful.
