### ISSUE TITLE
DI Compilation Fails When Setting queue_name_pattern with %delay% Placeholder in messenger.yaml

### ISSUE THREAD

**Issue by githoober** [jwage/phpamqplib-messenger#95]
When configuring a delay transport in messenger.yaml using the queue_name_pattern option with a placeholder, the Symfony Dependency Injection compilation fails.

Configuration Snippet:

```yaml
framework:
    messenger:
        transports:
            delay:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name_pattern: 'message-bus.delay-queue.%delay%'
```
Error Output:

```
[critical] Uncaught Exception: You have requested a non-existent parameter "delay" while loading extension "framework". Did you mean one of these: "... (other valid parameters listed)"?
```

Expected Behavior:

The %delay% placeholder should be interpreted as a runtime variable or a transport option placeholder, not a DI parameter. It should not trigger a container compilation error.

Steps to Reproduce:

- Configure the delay transport with the `queue_name_pattern` containing %delay%.
- Run `bin/console cache:clear` or trigger a DI compilation.
- Observe the critical error regarding a non-existent parameter.

Additional Context:

The error stems from Symfony interpreting `%delay%` as a container parameter instead of a placeholder intended for runtime replacement. This is blocking proper usage of dynamic queue naming for delay transports.
